#!/usr/bin/env python3
"""Word-cube guessing game (local CLI).

- Loads `word_cubes.txt` (generated by main2.py) or falls back to scanning cubes from
  `word_list_wordfreq.txt` if not present.
- Picks a random cube (4 rows), reveals 4 random letters, and prompts the player
  to guess the 4 rows (4-letter words) within a number of attempts.
- Provides per-letter feedback with colors: 🟩 correct, 🟨 present, ⬜ absent.

Usage:
  python3 wordcube_game.py        # runs interactive game
  python3 wordcube_game.py --reveal  # prints chosen cube and revealed letters (for testing)

"""
import argparse
import random
import sys
from pathlib import Path

CUR_DIR = Path('.')
CANDIDATE = CUR_DIR / 'word_lists' / 'word_cubes.txt'
CUBES_FILE = CANDIDATE if CANDIDATE.exists() else (CUR_DIR / 'word_cubes.txt')

WL_CAND = CUR_DIR / 'word_lists' / 'word_list_wordfreq.txt'
WORDLIST_FILE = WL_CAND if WL_CAND.exists() else (CUR_DIR / 'word_list_wordfreq.txt')

GREEN = '🟩'
YELLOW = '🟨'
GRAY = '⬜'


def load_cubes():
    cubes = []
    if CUBES_FILE.exists():
        text = CUBES_FILE.read_text()
        blocks = [b.strip() for b in text.split('\n\n') if b.strip()]
        for b in blocks:
            rows = [line.replace(' ', '').lower() for line in b.splitlines() if line.strip()]
            if len(rows) == 4 and all(len(r) == 4 for r in rows):
                cubes.append(rows)
    else:
        # try to synthesize cubes by picking four words whose columns are also words
        # (fallback: not ideal) — we'll simply return empty here which the caller handles
        pass
    return cubes


def feedback(guess, solution):
    # Color-coded feedback for a single 4-letter word
    result = [GRAY] * 4
    sol_chars = list(solution)
    # first pass greens
    for i, ch in enumerate(guess):
        if ch == sol_chars[i]:
            result[i] = GREEN
            sol_chars[i] = None
    # second pass yellows
    for i, ch in enumerate(guess):
        if result[i] == GREEN:
            continue
        if ch in sol_chars:
            result[i] = YELLOW
            sol_chars[sol_chars.index(ch)] = None
    return ''.join(result)


def print_grid(rows, revealed):
    for r in range(4):
        line = []
        for c in range(4):
            ch = rows[r][c]
            if (r, c) in revealed:
                line.append(ch.upper())
            else:
                line.append('.')
        print(' '.join(line))


def play_interactive(cube):
    attempts = 6
    revealed = set()
    # reveal 4 random distinct positions
    all_pos = [(r, c) for r in range(4) for c in range(4)]
    revealed = set(random.sample(all_pos, 4))

    print('A 4x4 word cube was chosen. 4 letters are revealed below:')
    print_grid(cube, revealed)
    print('\nGuess the 4 rows (each a 4-letter word). You have', attempts, 'attempts.')
    for attempt in range(1, attempts + 1):
        print(f'Attempt {attempt}/{attempts}')
        guesses = []
        for i in range(4):
            while True:
                try:
                    inp = input(f'Row {i+1}: ').strip().lower()
                except EOFError:
                    print('\nInput closed. Exiting.')
                    return
                if len(inp) != 4 or not inp.isalpha():
                    print('Please enter a 4-letter word (letters only).')
                    continue
                guesses.append(inp)
                break
        # show feedback per row
        all_green = True
        for i in range(4):
            fb = feedback(guesses[i], cube[i])
            print(f'Row {i+1}: {guesses[i].upper()}  {fb}')
            if fb != GREEN * 4:
                all_green = False
        if all_green:
            print('\nCongratulations — you solved the cube!')
            return
        else:
            print('\nCurrent revealed pattern:')
            print_grid(cube, revealed)
    print('\nOut of attempts. The cube was:')
    for row in cube:
        print(' '.join(row.upper()))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--reveal', action='store_true', help='print chosen cube and revealed letters and exit')
    args = parser.parse_args()

    cubes = load_cubes()
    if not cubes:
        print('No `word_cubes.txt` found or it contained no cubes. Run main2.py to generate cubes first.')
        sys.exit(1)

    cube = random.choice(cubes)
    if args.reveal:
        # reveal 4 random letters for debugging
        all_pos = [(r, c) for r in range(4) for c in range(4)]
        revealed = set(random.sample(all_pos, 4))
        print('Chosen cube (rows):')
        for row in cube:
            print(''.join(row))
        print('\nRevealed pattern:')
        print_grid(cube, revealed)
        return

    play_interactive(cube)


if __name__ == '__main__':
    main()
